services:
  psql-db:
    image: postgres:14-bookworm
    container_name: psql-db
    environment:
      - POSTGRES_PASSWORD=P4ssw0rd
      - POSTGRES_USER=admin
      - POSTGRES_DB=flask_db
    volumes:
      - ./psql-db.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - app-network

  web:
    depends_on:
      - psql-db
    build: .
    working_dir: /flask
    ports:
      - "8050:5000"
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    networks:
      - app-network

networks:
  app-network:
